### ISSUE TITLE
可否将插件傻瓜化

### ISSUE THREAD

**Issue by shermans** [malimaliao/kodi-addons#3]
大神你好，
KODI真是很好的软件。但是中文用户实在是越来越少了。
请问有没有可能，或者兴趣。
做一个傻瓜化的工具。小白们可以自己填入资源站的API。就可以打包生成KODI ADDON。
比如这种。
淘片,https://taopianapi.com/home/cjapi/as/mc/vod/xml
百度,https://m3u8.apibdzy.com/api.php/provide/vod/at/xml/

大慈大悲。功德无量。

**Comment by malimaliao** [comment]
[plugin.video.duolasousuo](https://github.com/malimaliao/kodi-addons/tree/matrix/plugin.video.duolasousuo) 實際上就是一個類似於這樣的視頻插件工具，只不過它還不夠成熟，目前具備搜索功能。但是它的搜索接口，就是來自於你訴說的資源性網站。

你可以嘗試，安裝這個插件之後，在插件設置中，可以更改你所需要的搜索引擎接口（目前僅支持資源站的接口搜索功能）

**Comment by malimaliao** [comment]
you can look readme.md

https://github.com/malimaliao/kodi-addons/blob/matrix/plugin.video.duolasousuo/README.md

**Comment by malimaliao** [comment]
如果你想打包成為自己的kodi程序分發，請注意不要用於商業用途。

以哆啦視頻搜索插件為例，你可以git clone該程序，然後修改它的 [settings.xml](https://github.com/malimaliao/kodi-addons/blob/matrix/plugin.video.duolasousuo/resources/settings.xml) 配置文件中的內置搜索引擎接口地址：
`<setting id="Duola_Local_Search_Engine" type="text" label="30104" default="https://api.123.com/api.php/provide/vod/" />`

如果你不需要該程序的雲端搜索功能，需要屏蔽它則可以刪除它的菜單：
`<setting id="Duola_play_style" type="select" label="30101" lvalues="30001|30002|30003"/>`
